export const RUNTIME = {
  python: "3.14",
  pythonFull: "3.14.7",
  django: "5.2.17",
  drf: "3.18.1",
};

/** Locked dependency versions - all verified to support Python 3.14. */
export const PINNED = {
  python: RUNTIME.pythonFull,
  Django: "5.2.17",
  "djangorestframework": "3.18.1",
  "django-filter": "26.1",
  "drf-spectacular": "0.30.0",
  "cors-headers": "4.9.0",
  "psycopg[binary]": "3.3.6",
};

export const METHOD_STYLES = {
  GET: "bg-sky-500/15 text-sky-300 ring-sky-500/30",
  POST: "bg-emerald-500/15 text-emerald-300 ring-emerald-500/30",
  PATCH: "bg-amber-500/15 text-amber-300 ring-amber-500/30",
  PUT: "bg-amber-500/15 text-amber-300 ring-amber-500/30",
  DELETE: "bg-rose-500/15 text-rose-300 ring-rose-500/30",
};

export const ROLE_LABELS = {
  owner: "Owner",
  admin: "Admin",
  member: "Member",
  viewer: "Viewer",
  any: "Any role",
  public: "No auth",
};

export const ENDPOINTS = [
  {
    id: "health",
    group: "Platform",
    method: "GET",
    path: "/api/health/",
    auth: false,
    roles: "public",
    summary: "Liveness probe with database connectivity check.",
    query: [],
  },
  {
    id: "seed",
    group: "Platform",
    method: "POST",
    path: "/api/seed/",
    auth: false,
    roles: "public",
    summary: "Load the two demo workspaces, projects, tasks and comments.",
    body: null,
  },
  {
    id: "register",
    group: "Authentication",
    method: "POST",
    path: "/api/auth/register/",
    auth: false,
    roles: "public",
    summary: "Sign up: creates a user, a workspace and an owner membership.",
    body: {
      full_name: "Ada Lovelace",
      email: "ada@example.com",
      password: "super-secret-1",
      workspace_name: "Ada's Workspace",
    },
  },
  {
    id: "token",
    group: "Authentication",
    method: "POST",
    path: "/api/auth/token/",
    auth: false,
    roles: "public",
    summary: "Exchange email + password for an access/refresh JWT pair.",
    body: { email: "ada@orbit.dev", password: "demo1234" },
  },
  {
    id: "refresh",
    group: "Authentication",
    method: "POST",
    path: "/api/auth/token/refresh/",
    auth: false,
    roles: "public",
    summary: "Rotate the refresh token and mint a new access token.",
    body: { refresh: "<paste a refresh token>" },
  },
  {
    id: "me",
    group: "Authentication",
    method: "GET",
    path: "/api/auth/me/",
    auth: true,
    roles: "any",
    summary: "Current user plus every workspace they belong to.",
    query: [],
  },
  {
    id: "me-patch",
    group: "Authentication",
    method: "PATCH",
    path: "/api/auth/me/",
    auth: true,
    roles: "any",
    summary: "Update your profile or rotate your password.",
    body: { full_name: "Ada King" },
  },
  {
    id: "tenants-list",
    group: "Workspaces",
    method: "GET",
    path: "/api/tenants/",
    auth: true,
    roles: "any",
    summary: "List the workspaces the token holder belongs to.",
    query: [],
  },
  {
    id: "tenants-create",
    group: "Workspaces",
    method: "POST",
    path: "/api/tenants/",
    auth: true,
    roles: "any",
    summary: "Create another workspace; the caller becomes its owner.",
    body: { name: "Apollo Robotics", plan: "pro" },
  },
  {
    id: "tenant-detail",
    group: "Workspaces",
    method: "GET",
    path: "/api/tenants/{id}/",
    auth: true,
    roles: "any",
    summary: "Workspace detail with plan usage statistics.",
    pathParams: ["id"],
    query: [],
  },
  {
    id: "tenant-patch",
    group: "Workspaces",
    method: "PATCH",
    path: "/api/tenants/{id}/",
    auth: true,
    roles: "owner, admin",
    summary: "Rename a workspace, change plan or feature-flag settings.",
    pathParams: ["id"],
    body: { name: "Northwind Labs", plan: "business" },
  },
  {
    id: "members-list",
    group: "Members & roles",
    method: "GET",
    path: "/api/members/",
    auth: true,
    roles: "any",
    summary: "Roster of the active workspace with roles.",
    query: [],
  },
  {
    id: "members-invite",
    group: "Members & roles",
    method: "POST",
    path: "/api/members/",
    auth: true,
    roles: "owner, admin",
    summary: "Add an existing user or create a pending invitation (seat limits apply).",
    body: { email: "new hire@orbit.dev", role: "member" },
  },
  {
    id: "member-patch",
    group: "Members & roles",
    method: "PATCH",
    path: "/api/members/{id}/",
    auth: true,
    roles: "owner, admin",
    summary: "Promote or demote a teammate; only owners may grant `owner`.",
    pathParams: ["id"],
    body: { role: "admin" },
  },
  {
    id: "projects-list",
    group: "Projects",
    method: "GET",
    path: "/api/projects/",
    auth: true,
    roles: "any",
    summary: "Paginated project list with open/total task counts.",
    query: ["status=active", "search=site", "archived=false", "limit=20", "offset=0", "ordering=-created_at"],
  },
  {
    id: "projects-create",
    group: "Projects",
    method: "POST",
    path: "/api/projects/",
    auth: true,
    roles: "owner, admin, member",
    summary: "Create a project - enforced by the workspace plan quota.",
    body: { name: "Billing Migration", key: "BILL", description: "Move to usage based billing.", status: "planning" },
  },
  {
    id: "project-detail",
    group: "Projects",
    method: "GET",
    path: "/api/projects/{id}/",
    auth: true,
    roles: "any",
    summary: "Project detail, board statistics and recent tasks.",
    pathParams: ["id"],
    query: [],
  },
  {
    id: "project-patch",
    group: "Projects",
    method: "PATCH",
    path: "/api/projects/{id}/",
    auth: true,
    roles: "owner, admin, member",
    summary: "Partial update of a project.",
    pathParams: ["id"],
    body: { status: "active", color: "#22c55e" },
  },
  {
    id: "project-delete",
    group: "Projects",
    method: "DELETE",
    path: "/api/projects/{id}/",
    auth: true,
    roles: "owner, admin",
    summary: "Delete a project and cascade its tasks.",
    pathParams: ["id"],
  },
  {
    id: "tasks-list",
    group: "Tasks",
    method: "GET",
    path: "/api/tasks/",
    auth: true,
    roles: "any",
    summary: "Task board query set with filters, search and ordering.",
    query: ["status=in_progress", "priority=high", "assignee=me", "search=sync", "limit=20", "ordering=-updated_at"],
  },
  {
    id: "tasks-create",
    group: "Tasks",
    method: "POST",
    path: "/api/tasks/",
    auth: true,
    roles: "owner, admin, member",
    summary: "Create a task; assignee must belong to the workspace.",
    body: {
      project: "<project uuid>",
      title: "Ship tenant isolation tests",
      description: "Cover cross-tenant read and write attempts.",
      status: "todo",
      priority: "high",
      story_points: 5,
    },
  },
  {
    id: "task-detail",
    group: "Tasks",
    method: "GET",
    path: "/api/tasks/{id}/",
    auth: true,
    roles: "any",
    summary: "Task detail with project and user stubs.",
    pathParams: ["id"],
    query: [],
  },
  {
    id: "task-patch",
    group: "Tasks",
    method: "PATCH",
    path: "/api/tasks/{id}/",
    auth: true,
    roles: "owner, admin, member",
    summary: "Move a task across the board or reassign it.",
    pathParams: ["id"],
    body: { status: "done", priority: "urgent" },
  },
  {
    id: "task-delete",
    group: "Tasks",
    method: "DELETE",
    path: "/api/tasks/{id}/",
    auth: true,
    roles: "owner, admin, member",
    summary: "Delete a task.",
    pathParams: ["id"],
  },
  {
    id: "comments-list",
    group: "Tasks",
    method: "GET",
    path: "/api/tasks/{id}/comments/",
    auth: true,
    roles: "any",
    summary: "Comment thread for a task.",
    pathParams: ["id"],
    query: [],
  },
  {
    id: "comments-create",
    group: "Tasks",
    method: "POST",
    path: "/api/tasks/{id}/comments/",
    auth: true,
    roles: "any",
    summary: "Comment on a task (viewers may discuss but not edit work).",
    pathParams: ["id"],
    body: { body: "Cutover looks good - scheduling for Thursday." },
  },
  {
    id: "activity",
    group: "Insights",
    method: "GET",
    path: "/api/activity/",
    auth: true,
    roles: "any",
    summary: "Per-tenant audit trail of every mutating action.",
    query: ["limit=25", "offset=0"],
  },
  {
    id: "summary",
    group: "Insights",
    method: "GET",
    path: "/api/summary/",
    auth: true,
    roles: "any",
    summary: "Dashboard aggregates: status mix, workload, progress per project.",
    query: [],
  },
];

export const DEMO_ACCOUNTS = [
  { email: "ada@orbit.dev", name: "Ada Lovelace", role: "Owner · Northwind Labs + Orbit Internal", tone: "text-indigo-300" },
  { email: "grace@orbit.dev", name: "Grace Hopper", role: "Admin · Northwind Labs", tone: "text-emerald-300" },
  { email: "linus@orbit.dev", name: "Linus Berg", role: "Member · Northwind Labs", tone: "text-sky-300" },
  { email: "margaret@orbit.dev", name: "Margaret Hamilton", role: "Viewer · Northwind Labs", tone: "text-amber-300" },
];

export const DEMO_PASSWORD = "demo1234";
